server:
  port: 9094
spring:
  application:
    name: demo-api
  redis:
    host: 127.0.0.1
    port: 6379
    password: 1234
    database: 0
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0

data:
  druid:
    url: jdbc:mysql://127.0.0.1:3306/demo1?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password:
mybatis:
#  mapper-locations: classpath:mapper/*Dao.xml
#  type-aliases-package: com.example.morning.demo.domain
  configuration:
    map-underscore-to-camel-case: true
    # 控制台打印sql语句,调试用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl