server:
  port: 9090
spring:
  application:
    name: demo-netty-ws
  redis:
    database: 0   # Redis数据库索引（默认为0）
    host: 127.0.0.1  # Redis服务器地址
    port: 6379  # Redis服务器连接端口
    password: 1234    # Redis服务器连接密码（默认为空）
    timeout: 500  # 连接超时时间（毫秒）
